### ISSUE TITLE
Fix failing text in xt/authors/calendar/acl.t

### ISSUE THREAD

**Issue by sdondley** [sdondley/moo-google#9] opened 2018-10-03 07:17 UTC
```
xt/author/calendar/acl.t .. 2/? user:pavesr@cpan.org at xt/author/calendar/acl.t line 77.
$VAR1 = {
          'error' => {
                     'message' => 'Provided acl id is invalid.',
                     'errors' => [
                                 'HASH(0x7f94bd832a28)'
                               ],
                     'code' => 403
                   }
        };
Use of uninitialized value in string eq at xt/author/calendar/acl.t line 93.

    #   Failed test 'kind seems like OK - calendar\#aclRule'
    #   at xt/author/calendar/acl.t line 93.
    # Looks like you failed 1 test of 2.

#   Failed test 'Acl->update'
#   at xt/author/calendar/acl.t line 98.
# Looks like you failed 1 test of 4.
xt/author/calendar/acl.t .. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/4 subtests

Test Summary Report
-------------------
xt/author/calendar/acl.t (Wstat: 256 Tests: 4 Failed: 1)
  Failed test:  4
  Non-zero exit status: 1
Files=1, Tests=4,  3 wallclock secs ( 0.02 usr  0.00 sys +  0.67 cusr  0.09 csys =  0.78 CPU)
Result: FAIL

```

**Comment by pscott-au** [comment] 2018-10-03 08:06
probably best if you reference your commit to solve this in the issue - then if is solved you can close the issue with a reference to the commit that includes the fix.

**Comment by sdondley** [comment] 2018-10-03 08:31
#e14dde4 just got the tests to run with dzil command. Didn't get them to actually pass.

**Comment by pscott-au** [comment] 2018-10-03 08:32
you should be able to see in your commit history - when you fix something
or make a functional change - commit.

**Comment by sdondley** [comment] 2018-10-03 08:32
i can see what I did I don't know why what I did worked.

**Comment by sdondley** [comment] 2018-10-03 08:33
Not going to commit it until I get a clear idea of what's going on. Not sure if I have the right fix or not.

**Comment by pscott-au** [comment] 2018-10-03 08:42
Commit often - rollbacks are cheap and it captures a point of time when
something happened - the commenting is also useful to trace the evolution.
Similarly - tag for release and use the base .. if you're using the base
from out perspective it's in production and that's what your master should
represent .. just my thoughts of course - feel completely free to ignore
and find your own path and I won't keep hassling you about it  :)

**Comment by sdondley** [comment] 2018-10-03 08:50
That's not really what is meant by commit often. By that is meant "don't do a big huge chunk of unrelated tasks and commit them together". there's not reason to commit something you are unsure you want to go forward with.

**Comment by pscott-au** [comment] 2018-10-03 08:55
Commit often is a general mantra (
https://stackoverflow.com/questions/28715628/in-git-why-is-it-good-to-commit-often
)
If something changes - commit it and create a rollback point - even if
you're not sure whether the issue is fixed. Also fix problems when you see
them - don't ignore them because you are trying to keep your commit clean.
This is how I work at least and it has served me well enough with others
once we're on the same page.

**Comment by pscott-au** [comment] 2018-10-03 08:57
So if a test works and you aren't compeltely sure why - examine the diffs -
if still not clear it could be an environment thing so commit anyway and
comment that you can't see why but test is now passing.

**Comment by sdondley** [comment] 2018-10-03 08:58
Like I said, I know what code was changed. I don't know why it worked.

**Closed** 2018-10-03 09:00 UTC
Labels: bug

**Comment by pscott-au** [comment] 2018-10-03 09:02
if you commit then we could both look at the change and isolate it.

**Comment by pscott-au** [comment] 2018-10-03 09:09
apologies - it's not my place to tell you how to run your repo - am just trying to guide you so that I can selfishly grab the bits that work without having to trawl through multiple branches or wait for changes to make it into the repo etc. In essence the important thing is the code change and being able to navigate through it - it is easy to try to over-engineer things resulting in a project management job more than a coding job - I'm more interested in getting things to work then copying best practices of environments that have problems that we don't. We are 2 ppl - potentially 3 or 4 working on a minor library that is miles from production ready but is of use to ppl who are willing to put a little time in. I want to maximise the utility as quickly as possible and streamline the flow. The tests are pretty crap and include a bunch of user specific stuff - I'm not getting much architectural stuff from reviewing them but I'll throw a few hours looking at the existing tests to see wahat I can come up with and send you links to my commits it I think they may be of interest.
